version: 2

project_name: tf-import-gen

before:
  hooks:
    - go mod download

builds:
  - main: .
    binary: tf-import-gen
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

homebrew_casks:
  - repository:
      owner: kishaningithub
      name: homebrew-tap
    homepage: https://github.com/kishaningithub/tf-import-gen
    description: Tool to generate terraform import statements to simplify state migrations from one terraform code base to another
    license: MIT
    # The binary is not signed and notarized, so remove the quarantine attribute to prevent Gatekeeper from blocking it
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tf-import-gen"]
          end

scoops:
  - repository:
      owner: kishaningithub
      name: scoop-bucket
    homepage: https://github.com/kishaningithub/tf-import-gen
    description: Tool to generate terraform import statements to simplify state migrations from one terraform code base to another
    license: MIT

nfpms:
  - id: tf-import-gen
    package_name: tf-import-gen
    homepage: https://github.com/kishaningithub/tf-import-gen
    description: Tool to generate terraform import statements to simplify state migrations from one terraform code base to another
    maintainer: Kishan B <kishancs46@gmail.com>
    license: MIT
    formats:
      - apk
      - deb
      - rpm

kos:
  - base_image: alpine
    repositories:
      - ghcr.io/kishaningithub/tf-import-gen
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - '{{.Version}}'
      - latest
    bare: true
    preserve_import_paths: false
